version: "3.7"

services: 
    app:
        image: node:latest
        command: | 
            bash -c "
            npm install pm2 -g &&
            mkdir -p /usr/src/cypher-backend &&
            yarn install --production && 
            ls -la &&
            pm2-runtime ./ecosystem.config.js --env production"
        working_dir: /usr/src/cypher-backend
        volumes: 
            - ./:/usr/src/cypher-backend
            - "site:/usr/src/static-site"
        ports: 
            - "9080:8080"
