version: "3.7"

services: 
    app:
        image: node:latest
        command: |
            npm install pm2 -g
            mkdir -p /usr/src/cypher-backend
            cd /usr/src/cypher-backend
            yarn install --production
            pm2-runtime ecosystem.config.js --env production
        volumes: 
            - "/var/www/:"
        ports: 
            - "9080:8080"


# INCOMPLETE DO NOT USE
