name: Cypher Image CI

on:
 push:
    branches: [ master, develop ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cypher-backend:latest 
     
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.ACTOR }}/cypher-backend
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.CR_PAT }}
        dockerfile: Dockerfile
        # tags: latest
